### ISSUE TITLE
Won't compile due to changes in C API

### ISSUE THREAD

**Issue by mxwell** [BelBES/mpl.pytorch#1]
Recently (4caea64d729728e3304e9c1e97081a6bdd463913) definition of T*Tensor stopped being available in C API externally. Because of that one cannot access fields like this:

```
int size = losses->size[0];
```

One possible solution is to get size of the tensor in Python and provide it into C as an argument.

**Comment by BelBES** [comment]
Hi,

Thanks, code was update for support latest version of pytorch.
